from django.urls import path
from . import views

urlpatterns = [
    path("",                              views.drive_home,     name="drive_home"),
    path("folder/<int:folder_pk>/",       views.drive_home,     name="drive_folder"),
    path("folder/create/",                views.create_folder,  name="drive_create_folder"),
    path("folder/<int:pk>/delete/",       views.delete_folder,  name="drive_delete_folder"),
    path("folder/<int:pk>/rename/",       views.rename_folder,  name="drive_rename_folder"),
    path("file/<int:pk>/rename/",         views.rename_file,    name="drive_rename_file"),
    path("upload-url/",                   views.upload_url,     name="drive_upload_url"),
    path("confirm/",                      views.confirm_upload,  name="drive_confirm"),
    path("download/<int:pk>/",            views.download_file,  name="drive_download"),
    path("view/<int:pk>/url/",            views.get_file_url,      name="drive_file_url"),
    path("view/<int:pk>/",               views.view_file,         name="drive_view"),
    path("thumb/<int:pk>/",              views.file_thumbnail,    name="drive_thumb"),
    path("delete/<int:pk>/",             views.delete_file,    name="drive_delete"),
    path("bulk-delete/",                 views.bulk_delete,    name="drive_bulk_delete"),
    path("archive/",                      views.archive_files,  name="drive_archive"),
    path("archive/view/",                 views.archive_view,   name="drive_archive_view"),
    path("restore/<int:pk>/",             views.restore_file,       name="drive_restore"),
    path("restore/",                      views.bulk_restore,       name="drive_bulk_restore"),
    path("bin/",                          views.recycle_bin,        name="drive_bin"),
    path("bin/<int:pk>/restore/",         views.restore_from_bin,   name="drive_bin_restore"),
    path("bin/<int:pk>/delete/",          views.permanent_delete,   name="drive_bin_delete"),
    path("bin/folder/<int:pk>/restore/",   views.restore_folder_from_bin, name="drive_bin_folder_restore"),
    path("bin/bulk-restore/",             views.bulk_bin_restore,   name="drive_bin_bulk_restore"),
    path("bin/bulk-delete/",              views.bulk_bin_delete,    name="drive_bin_bulk_delete"),
    path("folder/<int:pk>/zip/",          views.zip_folder,         name="drive_zip_folder"),
    path("folders/zip/",                  views.zip_folder,         name="drive_zip_folders"),
    path("job/<int:job_id>/status/",      views.job_status,         name="drive_job_status"),
]
